#%RAML 0.8
title: mobile phone payment API
mediaType: application/json

/plans:
  post:
    description: operator create new plan
    responses:
      201:
        description: success to create new plan
        headers:
          Location:
            example: "/plans/1"
      400:
        description: fail to create new plan
      404:
        description: fail to create new plan

  get:
    description: view plans
    responses:
      200:
        description: success to view plans
        body:
          application/json:
            example: |
              [{
                "price": "88",
                "data": "1GB",
                "call": 1000
              },
              {
                "price": "68",
                "data": "500MB",
                "call": 800
              }
              ]

  /{plan_id}:
    get:
      description: |
        view a specific plan
      responses:
        200:
          description: success to view plan
          body:
            application/json:
              example: |
                {
                  "price": "68",
                  "data": "500MB",
                  "call": 800
                }
        404:
          description: fail to view plan

/products:
  post:
    description: operator wants to create a new product
    responses:
      201:
        description: success to create new product
        headers:
          Location:
            example: "/products/1"
      400:
        description: fail to create new product
      404:
        description: fail to create new product

  get:
    description: view all products
    responses:
      200:
        description: success to view all products

  /{product_id}:
    get:
      description: view a specific product
      responses:
        200:
          description: success to view product
          body:
            application/json:
              example: |
                {
                  "type": "data",
                  "amount": "500MB",
                  "price": 30
                }
        404:
          description: fail to view product

/numbers:
  /{number}:
    get:
      description: user wants to view phone number status
      responses:
        200:
          description: success to view number status
          body:
            application/json:
              example: |
                {
                  "balance": 50,
                  "data": "543MB",
                  "call": 123
                }
        404:
          description: fail to view number status

    /plan:
      post:
        description: create plan for a number
        responses:
          201:
            description: success to create plan for number
            headers:
              Location:
                example: "/plans/1"
          400:
            description: fail to create plan for number
          404:
            description: fail to create plan for number

      get:
        description: view plan for a number
        responses:
          200:
            description: success to view plan for number
            body:
              application/json:
                example: |
                  {
                    "price": "68",
                    "data": "500MB",
                    "call": 800
                  }
          404:
            description: fail to view plan for number

      put:
        description: update plan for a number
        responses:
          204:
            description: success to update plan
          400:
            description: fail to update plan
          404:
            description: fail to update plan

    /purchases:
      get:
        description: user wants to view all purchases
        responses:
          200:
            description: success to view all purchases
            body:
              application/json:
                example: |
                  [{
                    "product": 1,
                    "price": 123,
                    "date": "2016.10.30"
                  },
                  {
                    "product": 2,
                    "price": 234,
                    "date": "2016.10.31"
                  }
                  ]
          404:
            description: fail to view all purchases

      /{purchase_id}:
        get:
          description: view a specific purchase
          responses:
            200:
              description: success to view a purchase
              body:
                application/json:
                  example: |
                    {
                      "product": 1,
                      "price": 123,
                      "date": "2016.10.30"
                    }
            404:
              description: fail to view a purchase

        /refill:
          get:
            description: view the data/call refill of a purchase on a number
            responses:
              200:
                description: success to view a refill
                body:
                  application/json:
                    example: |
                      {
                        "data": "500MB",
                        "call": 100
                      }
              404:
                description: fail to view a refill

    /plan-purchases:
      post:
        description: create a plan purchase on a number
        responses:
          201:
            description: success to create plan purchase
            headers:
              Location:
                example: "/purchases/1"
          400:
            description: fail to create plan purchase
          404:
            description: fail to create plan purchase

    /product-purchases:
      post:
        description: create a product purchase on a number
        responses:
          201:
            description: success to create product purchase
            headers:
              Location:
                example: "/purchases/2"
          400:
            description: fail to create product purchase
          404:
            description: fail to create product purchase

    /top-ups:
      post:
        description: create a top-up on a number
        responses:
          201:
            description: success to create a topup
            headers:
              Location:
                example: "/top-ups/1"
          400:
            description: fail to create a topup
          404:
            description: fail to create a topup

      get:
        description: view all top-ups of a number
        responses:
          200:
            description: success to view all topups
            body:
              application/json:
                example: |
                  [{
                    "amount": 100,
                    "date": "2016.10.30"
                  },
                  {
                    "amount": 200,
                    "date": "2016.10.31"
                  }]
          404:
            description: fail to view topups

      /{topup_id}:
        get:
          description: view a specific top-up on a number
          responses:
            200:
              description: success to view a top-up
              body:
                application/json:
                  example: |
                    {
                      "amount": 100,
                      "date": "2016.10.30"
                    }
            404:
              description: fail to view a top-up

    /usages:
      get:
        description: user wants to view all usages on a number
        responses:
          200:
            description: success to view usages
            body:
              application/json:
                example: |
                  [{
                    "type": "data",
                    "amount": "10MB",
                    "date": "2016.10.30",
                    "time": "19:40",
                    "location": "beijing",
                    "charge": 0,
                    "plan": 10
                  },
                  {
                    "type": "call",
                    "duration": 10,
                    "date": "2016.10.31",
                    "time": "12:40",
                    "number": 13800000000,
                    "outgoing": true,
                    "charge": 2,
                    "plan": 5
                  }]
          404:
            description: fail to view usages

      /{usage_id}:
        get:
          description: view a specific usage on a number
          responses:
            200:
              description: success to view a usage
              body:
                application/json:
                  example: |
                    {
                      "type": "call",
                      "duration": 10,
                      "date": "2016.10.31",
                      "time": "12:40",
                      "number": 13800000000,
                      "outgoing": true,
                      "charge": 0,
                      "plan": 10
                    }
            404:
              description: fail to view a usage

    /calls:
      post:
        description: create a call record on a number
        responses:
          201:
            description: success to create a call record
            headers:
              Location:
                example: "/usages/1"
          400:
            description: fail to create a call record
          404:
            description: fail to create a call record

    /data-usages:
      post:
        description: create a data usage record on a number
        responses:
          201:
            description: success to create a data usage
            headers:
              Location:
                example: "/usages/2"
          400:
            description: fail to create a data usage
          404:
            description: fail to create a data usage

    /plan-usages:
      post:
        description: create a plan usage record on a number
        responses:
          201:
            description:
              success to create plan usage on a number
            headers:
              Location:
                example: "/usages/3"
          400:
            description:
              fail to create plan usage on a number
          404:
            description:
              fail to create plan usage on a number
